//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrowdfindingApp.Core.Services.Projects.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationErrorMessages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrowdfindingApp.Core.Services.Projects.Resources.ValidationErrorMessages", typeof(ValidationErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продолжиетльность проекта должна быть больше чем 0 дней.
        /// </summary>
        internal static string ProjectValidationErrorKeys_DurationLessThanZero {
            get {
                return ResourceManager.GetString("ProjectValidationErrorKeys_DurationLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение {0} не является идентификационным номером паспорта.
        /// </summary>
        internal static string ProjectValidationErrorKeys_InvalidIdentificationPassportNo {
            get {
                return ResourceManager.GetString("ProjectValidationErrorKeys_InvalidIdentificationPassportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение {0} не является личным номером паспорта.
        /// </summary>
        internal static string ProjectValidationErrorKeys_InvalidPassportNo {
            get {
                return ResourceManager.GetString("ProjectValidationErrorKeys_InvalidPassportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введенный контактный номер &quot;{0}&quot; неправильного формата.
        /// </summary>
        internal static string ProjectValidationErrorKeys_InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("ProjectValidationErrorKeys_InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Адрес регистрации&quot; должно быть заполнено.
        /// </summary>
        internal static string ProjectValidationErrorKeys_MissingAuthorAddress {
            get {
                return ResourceManager.GetString("ProjectValidationErrorKeys_MissingAuthorAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Дата рождения&quot; должно быть заполнено.
        /// </summary>
        internal static string ProjectValidationErrorKeys_MissingAuthorDateOfBirth {
            get {
                return ResourceManager.GetString("ProjectValidationErrorKeys_MissingAuthorDateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Личный номер&quot; должно быть заполнено.
        /// </summary>
        internal static string ProjectValidationErrorKeys_MissingAuthorIdentificationNumber {
            get {
                return ResourceManager.GetString("ProjectValidationErrorKeys_MissingAuthorIdentificationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Отчество&quot; должно быть заполнено.
        /// </summary>
        internal static string ProjectValidationErrorKeys_MissingAuthorMiddleName {
            get {
                return ResourceManager.GetString("ProjectValidationErrorKeys_MissingAuthorMiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Имя&quot; должно быть заполнено.
        /// </summary>
        internal static string ProjectValidationErrorKeys_MissingAuthorName {
            get {
                return ResourceManager.GetString("ProjectValidationErrorKeys_MissingAuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Серия и номер&quot; должно быть заполнено.
        /// </summary>
        internal static string ProjectValidationErrorKeys_MissingAuthorPersonalNumber {
            get {
                return ResourceManager.GetString("ProjectValidationErrorKeys_MissingAuthorPersonalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Контактный номер&quot; должно быть заполнено.
        /// </summary>
        internal static string ProjectValidationErrorKeys_MissingAuthorPhone {
            get {
                return ResourceManager.GetString("ProjectValidationErrorKeys_MissingAuthorPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Фамилия&quot; должно быть заполнено.
        /// </summary>
        internal static string ProjectValidationErrorKeys_MissingAuthorSurname {
            get {
                return ResourceManager.GetString("ProjectValidationErrorKeys_MissingAuthorSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Финансовая цель проекта&quot; должно быть заполнено.
        /// </summary>
        internal static string ProjectValidationErrorKeys_MissingBudget {
            get {
                return ResourceManager.GetString("ProjectValidationErrorKeys_MissingBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Категория проекта&quot; должно быть заполнено.
        /// </summary>
        internal static string ProjectValidationErrorKeys_MissingCategory {
            get {
                return ResourceManager.GetString("ProjectValidationErrorKeys_MissingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Длительность проекта&quot; должно быть заполнено.
        /// </summary>
        internal static string ProjectValidationErrorKeys_MissingDuration {
            get {
                return ResourceManager.GetString("ProjectValidationErrorKeys_MissingDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Полное описание проекта&quot; должно быть заполнено.
        /// </summary>
        internal static string ProjectValidationErrorKeys_MissingFullDescription {
            get {
                return ResourceManager.GetString("ProjectValidationErrorKeys_MissingFullDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Место проведения проекта&quot; должно быть заполнено.
        /// </summary>
        internal static string ProjectValidationErrorKeys_MissingLocation {
            get {
                return ResourceManager.GetString("ProjectValidationErrorKeys_MissingLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавьте хотя бы один часто задаваемый вопрос.
        /// </summary>
        internal static string ProjectValidationErrorKeys_MissingQuestions {
            get {
                return ResourceManager.GetString("ProjectValidationErrorKeys_MissingQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавьте хотя бы одно вознаграждение.
        /// </summary>
        internal static string ProjectValidationErrorKeys_MissingRewards {
            get {
                return ResourceManager.GetString("ProjectValidationErrorKeys_MissingRewards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Краткое описание проекта&quot; должно быть заполнено.
        /// </summary>
        internal static string ProjectValidationErrorKeys_MissingShortDescription {
            get {
                return ResourceManager.GetString("ProjectValidationErrorKeys_MissingShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Названия проекта&quot; должно быть заполнено.
        /// </summary>
        internal static string ProjectValidationErrorKeys_MissingTitle {
            get {
                return ResourceManager.GetString("ProjectValidationErrorKeys_MissingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Дата выдачи документа&quot; должно быть заполнено.
        /// </summary>
        internal static string ProjectValidationErrorKeys_MissingWhenGivenDocument {
            get {
                return ResourceManager.GetString("ProjectValidationErrorKeys_MissingWhenGivenDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Кем выдан документ&quot; должно быть заполнено.
        /// </summary>
        internal static string ProjectValidationErrorKeys_MissingWhomGivenDocument {
            get {
                return ResourceManager.GetString("ProjectValidationErrorKeys_MissingWhomGivenDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Превышена максимальная длина ({0}) поля &quot;Краткое описание проекта&quot;.
        /// </summary>
        internal static string ProjectValidationErrorKeys_ToLargeShortdescriptionLength {
            get {
                return ResourceManager.GetString("ProjectValidationErrorKeys_ToLargeShortdescriptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ответ на вопрос не может быть пустым.
        /// </summary>
        internal static string QuestionValidationErrorKeys_MissingAnswer {
            get {
                return ResourceManager.GetString("QuestionValidationErrorKeys_MissingAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вопрос не может быть пустым.
        /// </summary>
        internal static string QuestionValidationErrorKeys_MissingQuestion {
            get {
                return ResourceManager.GetString("QuestionValidationErrorKeys_MissingQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Страны доставки не могут содержать пустых значений.
        /// </summary>
        internal static string RewardValidationErrorKeys_EmptyDeliveryCountries {
            get {
                return ResourceManager.GetString("RewardValidationErrorKeys_EmptyDeliveryCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хотя бы одна страна доставки должны быть добавлена .
        /// </summary>
        internal static string RewardValidationErrorKeys_MissingDeliveryCountries {
            get {
                return ResourceManager.GetString("RewardValidationErrorKeys_MissingDeliveryCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата доставки вознаграждения должна быть заполнена.
        /// </summary>
        internal static string RewardValidationErrorKeys_MissingDeliveryDate {
            get {
                return ResourceManager.GetString("RewardValidationErrorKeys_MissingDeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Описание вознаграждения&quot; должно быть заполнено.
        /// </summary>
        internal static string RewardValidationErrorKeys_MissingDescription {
            get {
                return ResourceManager.GetString("RewardValidationErrorKeys_MissingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стоимость вознаграждения должна быть заполнена.
        /// </summary>
        internal static string RewardValidationErrorKeys_MissingPrice {
            get {
                return ResourceManager.GetString("RewardValidationErrorKeys_MissingPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле &quot;Название вознаграждения&quot; должно быть заполнено.
        /// </summary>
        internal static string RewardValidationErrorKeys_MissingTitle {
            get {
                return ResourceManager.GetString("RewardValidationErrorKeys_MissingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Страны доставки содержат невалидные идентификаторы.
        /// </summary>
        internal static string RewardValidationErrorKeys_WrongDeliveryCountriesIds {
            get {
                return ResourceManager.GetString("RewardValidationErrorKeys_WrongDeliveryCountriesIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ограничение вознаграждения по количеству должно быть больше 0.
        /// </summary>
        internal static string RewardValidationErrorKeys_WrongLimitValue {
            get {
                return ResourceManager.GetString("RewardValidationErrorKeys_WrongLimitValue", resourceCulture);
            }
        }
    }
}
